spring:
  application:
    name: myblog
  threads:
    virtual:
      enabled: true
  datasource:
    url: ${APP_BLOG_PG_URL}
    username: ${APP_BLOG_PG_USERNAME}
    password: ${APP_BLOG_PG_PASSWORD}
  liquibase:
    url: ${spring.datasource.url}
    user: ${spring.datasource.username}
    password: ${spring.datasource.password}
  docker:
    compose:
      enabled: false
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 20MB
server:
  port: ${APP_BLOG_PORT}
